name: _Shared Deploy Cloud Run

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      google_cloud_project_id:
        required: true
        type: string
      google_cloud_region:
        required: true
        type: string
      google_cloud_workload_identity_provider:
        required: true
        type: string
      google_cloud_service_account:
        required: true
        type: string
      cloudrun_service_account:
        required: true
        type: string
    secrets:
      CONTENTFUL_SPACE_ID:
        required: true
      CONTENTFUL_ACCESS_TOKEN:
        required: true

env:
  APP_ID: blog

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v2
    
    - name: Auth Workload identity
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ inputs.google_cloud_workload_identity_provider }}
        service_account: ${{ inputs.google_cloud_service_account }}

    - name: authenticate registry
      run: gcloud auth configure-docker "${{ inputs.google_cloud_region }}-docker.pkg.dev"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - id: build_push
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{ inputs.google_cloud_region }}-docker.pkg.dev/${{ inputs.google_cloud_project_id }}/server/${{ env.APP_ID }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Generate Cloud Run YAML with Environment Variables
      run: envsubst < ./.github/resources/cloudrun_spec.yml  > ./.github/resources/cloudrun_spec_env.yml
      env:
        ENV_NAME: ${{ inputs.env_name }}
        IMAGE: ${{ inputs.google_cloud_region }}-docker.pkg.dev/${{ inputs.google_cloud_project_id }}/server/${{ env.APP_ID }}@${{ steps.build_push.outputs.digest }}
        SERVICE_ACCOUNT: ${{ inputs.cloudrun_service_account }}
        CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
        CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

    - name: Deploy Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        region: ${{ inputs.google_cloud_region }}
        metadata: ./.github/resources/cloudrun_spec_env.yml
